import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

/**
 * Export scan results to JSON format
 */
export function exportToJSON(scanData) {
  const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(scanData, null, 2));
  const downloadAnchor = document.createElement('a');
  downloadAnchor.setAttribute("href", dataStr);
  downloadAnchor.setAttribute("download", `subscope-${scanData.targetDomain}-results.json`);
  document.body.appendChild(downloadAnchor);
  downloadAnchor.click();
  downloadAnchor.remove();
}

/**
 * Export scan results to CSV format
 */
export function exportToCSV(scanData) {
  const headers = ["Subdomain", "Status", "IP / Record", "Discovery Method", "First Seen", "Details"];
  const rows = scanData.results.map(item => [
    `"${item.subdomain}"`,
    `"${item.status}"`,
    `"${item.ip || 'N/A'}"`,
    `"${item.discoveryMethod}"`,
    `"${item.firstSeen || 'N/A'}"`,
    `"${(item.detailsExplanation || '').replace(/"/g, '""')}"`
  ]);

  const csvContent = "data:text/csv;charset=utf-8," 
    + [headers.join(','), ...rows.map(e => e.join(','))].join('\n');

  const downloadAnchor = document.createElement('a');
  downloadAnchor.setAttribute("href", encodeURI(csvContent));
  downloadAnchor.setAttribute("download", `subscope-${scanData.targetDomain}-results.csv`);
  document.body.appendChild(downloadAnchor);
  downloadAnchor.click();
  downloadAnchor.remove();
}

/**
 * Export scan results to PDF report with official disclaimer header
 */
export function exportToPDF(scanData) {
  const doc = new jsPDF();

  // Header Banner
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, 210, 36, 'F');

  doc.setTextColor(6, 182, 212); // cyan-500
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('SubScope Security Assessment', 14, 18);

  doc.setTextColor(244, 63, 94); // rose-500
  doc.setFontSize(10);
  doc.text('AUTHORIZED SECURITY ASSESSMENT – DEMONSTRATION', 14, 28);

  // Meta Section
  doc.setTextColor(30, 41, 59); // slate-800
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Assessment Metadata', 14, 46);

  doc.setFontSize(9.5);
  doc.setFont('helvetica', 'normal');
  doc.text(`Target Domain: ${scanData.targetDomain}`, 14, 53);
  doc.text(`Scan Date & Time: ${new Date(scanData.scanDate).toLocaleString()}`, 14, 60);
  doc.text(`Authorization Status: Confirmed Owner / Authorized Assessor`, 14, 67);
  doc.text(`Execution Type: ${scanData.isDemo ? 'Demonstration Mode (Simulated Data)' : 'Active & Passive Enumeration'}`, 14, 74);

  // Executive Summary Box
  doc.setFillColor(241, 245, 249);
  doc.roundedRect(120, 44, 76, 35, 3, 3, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(15, 23, 42);
  doc.text('Scan Summary', 125, 52);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.text(`Total Discovered: ${scanData.summary.totalDiscovered}`, 125, 60);
  doc.text(`Resolved: ${scanData.summary.resolved}`, 125, 66);
  doc.text(`Unresolved: ${scanData.summary.unresolved}`, 125, 72);
  doc.text(`Duration: ${scanData.durationSeconds || '2.0'}s`, 125, 78);

  // Table of Discovered Subdomains
  const tableData = scanData.results.map(item => [
    item.subdomain,
    item.status,
    item.ip || 'N/A',
    item.discoveryMethod,
    item.firstSeen || 'N/A'
  ]);

  doc.autoTable({
    startY: 86,
    head: [['Subdomain', 'Status', 'IP / Record', 'Discovery Method', 'First Seen']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [15, 23, 42], textColor: [6, 182, 212], fontStyle: 'bold', fontSize: 9 },
    bodyStyles: { fontSize: 8.5, textColor: [30, 41, 59] },
    alternateRowStyles: { fillColor: [248, 250, 252] },
  });

  // Footer Disclaimer
  const finalY = doc.lastAutoTable ? doc.lastAutoTable.finalY + 12 : 250;
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text('NOTICE: This report is generated by SubScope as an educational cybersecurity prototype.', 14, Math.min(finalY, 280));
  doc.text('Only perform security assessments against infrastructure you own or have explicit written permission to scan.', 14, Math.min(finalY + 5, 285));

  doc.save(`subscope-${scanData.targetDomain}-security-report.pdf`);
}
